from typing import List, Optional
from datetime import datetime, timezone, date

from fastapi import APIRouter, Depends, HTTPException, status
from google.oauth2 import id_token
from google.auth.transport import requests as google_requests

from app.core.database import get_db
from app.core.config import settings

from app.core.security import (
    verify_password,
    get_password_hash,
    create_access_token,
    create_refresh_token,
    decode_token,
)

from app.core.dependencies import (
    get_current_user,
    RoleChecker,
)

from app.models.user import User, UserRole
from app.models.business import Business, BusinessUser
from app.models.employee import Employee

from app.schemas.auth import (
    UserRegister,
    UserLogin,
    Token,
    RefreshTokenRequest,
    UserResponse,
    PasswordResetRequest,
    PasswordResetConfirm,
    UserUpdate,
    UserCreateByAdmin,
    WorkerRegister,
    SocialLoginRequest,
)

from app.schemas.common import MessageResponse


router = APIRouter(
    prefix="/auth",
    tags=["Authentication"],
)


# ============================================================
# HELPERS
# ============================================================

def get_user_business(user: User):
    """
    Return the business associated with the user.
    Supports both owner and worker/member accounts.
    """

    if user.owned_business:
        return user.owned_business

    if user.business_membership:
        return user.business_membership.business

    return None


def build_business_response(user: User):
    """
    Build the business object returned after login/register.
    """

    business = get_user_business(user)

    if not business:
        return None

    return {
        "id": business.id,
        "unique_code": business.unique_code,
        "name": business.name,
        "currency": business.currency,
        "currency_symbol": business.currency_symbol,
    }


def create_auth_response(user: User):
    """
    Create access/refresh tokens and business information.
    """

    business = get_user_business(user)

    business_id = None

    if business:
        business_id = business.id

    access_token = create_access_token(
        user.id,
        role=user.role.value,
        business_id=business_id,
    )

    refresh_token = create_refresh_token(
        user.id,
    )

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer",
        "user": user,
        "business": build_business_response(user),
    }


# ============================================================
# OWNER REGISTRATION
# ============================================================

@router.post(
    "/register",
    response_model=Token,
)
def register(
    user_in: UserRegister,
    db: Session = Depends(get_db),
):
    # --------------------------------------------------------
    # Check existing email
    # --------------------------------------------------------

    existing_user = (
        db.query(User)
        .filter(
            User.email == user_in.email.lower()
        )
        .first()
    )

    if existing_user:
        raise HTTPException(
            status_code=400,
            detail="Email already registered",
        )

    # --------------------------------------------------------
    # Create user
    # --------------------------------------------------------

    user = User(
        email=user_in.email.lower(),
        hashed_password=get_password_hash(
            user_in.password
        ),
        first_name=user_in.first_name.strip(),
        last_name=user_in.last_name.strip(),
        phone=user_in.phone,
        role=UserRole.BUSINESS_OWNER,
        is_active=True,
        is_verified=True,
        auth_provider="local",
        provider_user_id=None,
    )

    db.add(user)
    db.flush()

    # --------------------------------------------------------
    # Create business
    #
    # unique_code is generated by PostgreSQL server default.
    # DO NOT manually set unique_code here.
    # --------------------------------------------------------

    business = Business(
        owner_id=user.id,
        name=user_in.business_name.strip(),
        business_type=user_in.business_type,
        industry=user_in.industry,
        email=(
            user_in.business_email.lower()
            if user_in.business_email
            else None
        ),
        phone=user_in.business_phone,
        address=user_in.address,
        city=user_in.city,
        state=user_in.state,
        country=user_in.country,
        pincode=user_in.pincode,
        tax_type=user_in.tax_type,
        tax_id_gst=user_in.tax_id_gst,
        pan=user_in.pan,
        business_registration_number=(
            user_in.business_registration_number
        ),
    )

    db.add(business)
    db.flush()

    # --------------------------------------------------------
    # Commit
    # --------------------------------------------------------

    db.commit()

    db.refresh(user)
    db.refresh(business)

    # --------------------------------------------------------
    # Tokens
    # --------------------------------------------------------

    access_token = create_access_token(
        user.id,
        role=user.role.value,
        business_id=business.id,
    )

    refresh_token = create_refresh_token(
        user.id,
    )

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer",
        "user": user,
        "business": {
            "id": business.id,
            "unique_code": business.unique_code,
            "name": business.name,
            "currency": business.currency,
            "currency_symbol": business.currency_symbol,
        },
    }


# ============================================================
# WORKER REGISTRATION
# ============================================================

@router.post(
    "/register-worker",
    response_model=Token,
)
def register_worker(
    worker_in: WorkerRegister,
    db: Session = Depends(get_db),
):
    # --------------------------------------------------------
    # Normalize business code
    # --------------------------------------------------------

    business_code = (
        worker_in.business_code
        .strip()
        .upper()
    )

    # --------------------------------------------------------
    # Find business
    # --------------------------------------------------------

    business = (
        db.query(Business)
        .filter(
            Business.unique_code == business_code
        )
        .first()
    )

    if not business:
        raise HTTPException(
            status_code=404,
            detail="Invalid business unique code",
        )

    # --------------------------------------------------------
    # Check existing email
    # --------------------------------------------------------

    existing_user = (
        db.query(User)
        .filter(
            User.email == worker_in.email.lower()
        )
        .first()
    )

    if existing_user:
        raise HTTPException(
            status_code=400,
            detail="Email already registered",
        )

    # --------------------------------------------------------
    # Create worker
    # --------------------------------------------------------

    user = User(
        email=worker_in.email.lower(),
        hashed_password=get_password_hash(
            worker_in.password
        ),
        first_name=worker_in.first_name.strip(),
        last_name=worker_in.last_name.strip(),
        phone=worker_in.phone,
        role=UserRole.EMPLOYEE,
        is_active=True,
        is_verified=True,
        auth_provider="local",
        provider_user_id=None,
    )

    db.add(user)
    db.flush()

    # --------------------------------------------------------
    # Business membership
    # --------------------------------------------------------

    membership = BusinessUser(
        business_id=business.id,
        user_id=user.id,
    )

    db.add(membership)

    # --------------------------------------------------------
    # Commit
    # --------------------------------------------------------

    db.commit()

    db.refresh(user)
    db.refresh(business)

    # --------------------------------------------------------
    # Tokens
    # --------------------------------------------------------

    access_token = create_access_token(
        user.id,
        role=user.role.value,
        business_id=business.id,
    )

    refresh_token = create_refresh_token(
        user.id,
    )

    return {
        "access_token": access_token,
        "refresh_token": refresh_token,
        "token_type": "bearer",
        "user": user,
        "business": {
            "id": business.id,
            "unique_code": business.unique_code,
            "name": business.name,
            "currency": business.currency,
            "currency_symbol": business.currency_symbol,
        },
    }


# ============================================================
# LOGIN
# ============================================================

@router.post(
    "/login",
    response_model=Token,
)
def login(
    user_in: UserLogin,
    db: Session = Depends(get_db),
):
    # --------------------------------------------------------
    # Find user
    # --------------------------------------------------------

    user = (
        db.query(User)
        .filter(
            User.email == user_in.email.lower()
        )
        .first()
    )

    # --------------------------------------------------------
    # Invalid credentials
    # --------------------------------------------------------

    if not user:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password",
        )

    # --------------------------------------------------------
    # Verify password
    # --------------------------------------------------------

    if not verify_password(
        user_in.password,
        user.hashed_password,
    ):
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid email or password",
        )

    # --------------------------------------------------------
    # Account status
    # --------------------------------------------------------

    if not user.is_active:
        raise HTTPException(
            status_code=403,
            detail="Account is deactivated",
        )

    # --------------------------------------------------------
    # Return authentication response
    # --------------------------------------------------------

    return create_auth_response(user)


# ============================================================
# SOCIAL LOGIN
# ============================================================

@router.post(
    "/social-login",
    response_model=Token,
)
def social_login(
    request: SocialLoginRequest,
    db: Session = Depends(get_db),
):
    """Authenticate a user with a verified Google ID token."""
    provider = request.provider.strip().lower()

    if provider != "google":
        raise HTTPException(status_code=400, detail="Only Google authentication is configured")

    if not request.id_token.strip():
        raise HTTPException(status_code=400, detail="Google identity token is required")

    google_client_id = getattr(settings, "GOOGLE_CLIENT_ID", None)
    if not google_client_id:
        raise HTTPException(status_code=500, detail="Google authentication is not configured")

    try:
        google_user = id_token.verify_oauth2_token(
            request.id_token,
            google_requests.Request(),
            google_client_id,
        )
    except ValueError:
        raise HTTPException(status_code=401, detail="Invalid or expired Google identity token")

    provider_user_id = google_user.get("sub")
    email = google_user.get("email")
    email_verified = google_user.get("email_verified", False)

    if not provider_user_id or not email:
        raise HTTPException(status_code=401, detail="Google account information is incomplete")

    if not email_verified:
        raise HTTPException(status_code=403, detail="Google email is not verified")

    email = email.lower().strip()
    first_name = (google_user.get("given_name") or google_user.get("name", "").split(" ")[0] or "Google").strip()
    last_name = (google_user.get("family_name") or "").strip()
    avatar_url = google_user.get("picture")

    user = db.query(User).filter(User.email == email).first()

    if not user:
        raise HTTPException(
            status_code=404,
            detail="No VyaparX account exists for this Google email. Please register first.",
        )

    if not user.is_active:
        raise HTTPException(status_code=403, detail="Account is deactivated")

    if user.auth_provider == "local":
        raise HTTPException(
            status_code=409,
            detail="An account with this email already exists using email/password login. Please use your password.",
        )

    if user.auth_provider != "google":
        raise HTTPException(status_code=409, detail="This account uses a different authentication provider")

    if user.provider_user_id != provider_user_id:
        raise HTTPException(status_code=409, detail="Google account does not match the registered account")

    user.first_name = first_name
    user.last_name = last_name
    user.avatar_url = avatar_url
    user.is_verified = True

    db.add(user)
    db.commit()
    db.refresh(user)

    return create_auth_response(user)


# ============================================================
# REFRESH TOKEN
# ============================================================

@router.post(
    "/refresh",
    response_model=dict,
)
def refresh_token_endpoint(
    req: RefreshTokenRequest,
    db: Session = Depends(get_db),
):
    payload = decode_token(
        req.refresh_token,
        is_refresh=True,
    )

    if (
        not payload
        or payload.get("type") != "refresh"
    ):
        raise HTTPException(
            status_code=401,
            detail="Invalid or expired refresh token",
        )

    user_id = payload.get("sub")

    user = (
        db.query(User)
        .filter(User.id == user_id)
        .first()
    )

    if not user or not user.is_active:
        raise HTTPException(
            status_code=401,
            detail="User not found or inactive",
        )

    business = get_user_business(user)

    business_id = (
        business.id
        if business
        else None
    )

    new_access_token = create_access_token(
        user.id,
        role=user.role.value,
        business_id=business_id,
    )

    return {
        "access_token": new_access_token,
        "token_type": "bearer",
    }


# ============================================================
# CURRENT USER
# ============================================================

@router.get(
    "/me",
    response_model=UserResponse,
)
def get_me(
    current_user: User = Depends(
        get_current_user
    ),
):
    return current_user


# ============================================================
# UPDATE CURRENT USER
# ============================================================

@router.put(
    "/me",
    response_model=UserResponse,
)
def update_me(
    user_in: UserUpdate,
    current_user: User = Depends(
        get_current_user
    ),
    db: Session = Depends(get_db),
):
    if user_in.first_name:
        current_user.first_name = (
            user_in.first_name.strip()
        )

    if user_in.last_name:
        current_user.last_name = (
            user_in.last_name.strip()
        )

    if user_in.phone is not None:
        current_user.phone = user_in.phone

    if user_in.avatar_url is not None:
        current_user.avatar_url = (
            user_in.avatar_url
        )

    current_user.updated_at = datetime.now(
        timezone.utc
    )

    db.add(current_user)
    db.commit()
    db.refresh(current_user)

    return current_user


# ============================================================
# FORGOT PASSWORD
# ============================================================

@router.post(
    "/forgot-password",
    response_model=MessageResponse,
)
def forgot_password(
    req: PasswordResetRequest,
    db: Session = Depends(get_db),
):
    user = (
        db.query(User)
        .filter(
            User.email == req.email.lower()
        )
        .first()
    )

    # --------------------------------------------------------
    # Do not reveal whether email exists
    # --------------------------------------------------------

    if not user:
        return MessageResponse(
            success=True,
            message=(
                "If that email is registered, "
                "password reset instructions "
                "have been generated."
            ),
        )

    reset_token = create_access_token(
        user.id,
        role=user.role.value,
    )

    return MessageResponse(
        success=True,
        message=(
            "Password reset token "
            "generated successfully"
        ),
        data={
            "reset_token": reset_token,
        },
    )


# ============================================================
# RESET PASSWORD
# ============================================================

@router.post(
    "/reset-password",
    response_model=MessageResponse,
)
def reset_password(
    req: PasswordResetConfirm,
    db: Session = Depends(get_db),
):
    payload = decode_token(
        req.token
    )

    if not payload:
        raise HTTPException(
            status_code=400,
            detail="Invalid or expired reset token",
        )

    user_id = payload.get("sub")

    user = (
        db.query(User)
        .filter(User.id == user_id)
        .first()
    )

    if not user:
        raise HTTPException(
            status_code=404,
            detail="User not found",
        )

    user.hashed_password = (
        get_password_hash(
            req.new_password
        )
    )

    user.auth_provider = "local"

    db.add(user)
    db.commit()

    return MessageResponse(
        success=True,
        message=(
            "Password updated successfully. "
            "Please login."
        ),
    )


# ============================================================
# LIST BUSINESS USERS
# ============================================================

@router.get(
    "/users",
    response_model=List[UserResponse],
)
def list_business_users(
    current_user: User = Depends(
        RoleChecker(
            [
                UserRole.BUSINESS_OWNER,
                UserRole.MANAGER,
            ]
        )
    ),
    db: Session = Depends(get_db),
):
    business = get_user_business(
        current_user
    )

    if not business:
        return [current_user]

    business_users = (
        db.query(User)
        .join(BusinessUser)
        .filter(
            BusinessUser.business_id
            == business.id
        )
        .all()
    )

    # Owner may not have a BusinessUser row.
    if (
        current_user.role
        == UserRole.BUSINESS_OWNER
        and current_user not in business_users
    ):
        business_users.insert(
            0,
            current_user,
        )

    return business_users


# ============================================================
# CREATE EMPLOYEE USER BY OWNER
# ============================================================

@router.post(
    "/users",
    response_model=UserResponse,
)
def create_employee_user(
    user_in: UserCreateByAdmin,
    current_user: User = Depends(
        RoleChecker(
            [UserRole.BUSINESS_OWNER]
        )
    ),
    db: Session = Depends(get_db),
):
    # --------------------------------------------------------
    # Owner must have business
    # --------------------------------------------------------

    if not current_user.owned_business:
        raise HTTPException(
            status_code=400,
            detail=(
                "No active business registered "
                "for current user"
            ),
        )

    # --------------------------------------------------------
    # Check email
    # --------------------------------------------------------

    existing = (
        db.query(User)
        .filter(
            User.email
            == user_in.email.lower()
        )
        .first()
    )

    if existing:
        raise HTTPException(
            status_code=400,
            detail="Email already registered",
        )

    business = (
        current_user.owned_business
    )

    # --------------------------------------------------------
    # Create user
    # --------------------------------------------------------

    new_user = User(
        email=user_in.email.lower(),
        hashed_password=get_password_hash(
            user_in.password
        ),
        first_name=user_in.first_name.strip(),
        last_name=user_in.last_name.strip(),
        phone=user_in.phone,
        role=user_in.role,
        is_active=True,
        is_verified=True,
        auth_provider="local",
        provider_user_id=None,
    )

    db.add(new_user)
    db.flush()

    # --------------------------------------------------------
    # Business membership
    # --------------------------------------------------------

    membership = BusinessUser(
        business_id=business.id,
        user_id=new_user.id,
    )

    db.add(membership)

    # --------------------------------------------------------
    # Optional employee record
    # --------------------------------------------------------

    employee = Employee(
        business_id=business.id,
        user_id=new_user.id,
        first_name=new_user.first_name,
        last_name=new_user.last_name,
        email=new_user.email,
        phone=new_user.phone,
        designation="Staff",
        department=(
            user_in.department
            or "Sales"
        ),
        joining_date=date.today(),
        is_active="true",
    )

    db.add(employee)

    db.commit()
    db.refresh(new_user)

    return new_user